// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byqosxazhtowthtbgiiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5cW9zeGF6aHRvd3RodGJnaWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTA4MzksImV4cCI6MjA3MDEyNjgzOX0.pl310jlxx2289G2oHUoVARJydehcQaDo1oD3gYyUS7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});